name: Tests

on:
  push:
    branches:
      - main

  pull_request:
    types: [ opened, synchronize, reopened ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php: [  8.0, 8.1, 8.2 ]
        laravel: [ 9.*, 10.* ]
        dependency-version: [ prefer-lowest, prefer-stable ]
        include:
          - laravel: 9.*
            testbench: 7.*

          - laravel: 10.*
            testbench: 8.*

        exclude:
            # PHP 8.2 requires Laravel 9.33 at least, so skip lowest
          - laravel: 9.*
            php: 8.2
            dependency-version: prefer-lowest

            # Laravel 10 requires PHP 8.1
          - laravel: 10.*
            php: 8.0

    name: P${{ matrix.php }} / L${{ matrix.laravel }} / ${{ matrix.dependency-version }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ~/.composer/cache/files
          key: dependencies-laravel-${{ matrix.laravel }}-php-${{ matrix.php }}-composer-${{ hashFiles('composer.json') }}

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, bcmath, soap, intl, gd, exif, iconv, imagick
          coverage: none

      - name: Install dependencies
        run: |
          composer self-update ${{ matrix.composer-version }}
          composer require "laravel/framework:${{ matrix.laravel }}" "orchestra/testbench:${{ matrix.testbench }}" --no-interaction --no-update
          composer update --${{ matrix.dependency-version }} --prefer-dist --no-interaction

      - name: Execute tests
        run: vendor/bin/phpunit
